version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:43"
      timezone: "Europe/London"
    ignore:
      # Node
      - dependency-name: "@types/node"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    reviewers:
      - "anaarezo"
