name: Reviewer to Assignee

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-reviewer-as-assignee:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add Reviewer as Assignee
        uses: actions/github-script@v5
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const reviewer = context.payload.requested_reviewer.login;

            // Add the reviewer as an assignee to the PR
            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number: prNumber,
              assignees: [reviewer],
            });
