name: Dependabot Auto-merge
on:
  workflow_dispatch:
    inputs:
      prBranch:
        description: "Branch of the upstream PR"
        required: true
permissions:
  pull-requests: write
  contents: write
jobs:
  conditionally-merge-dependabot-pr:
    name: Merge PR if checks are successful
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.prBranch }}
      - name: Wait for PR checks to complete
        id: pr-checks
        run: gh pr checks --fail-fast --watch --interval 30
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # This step will fail if not all checks are passing
      # This will prevent the PR from being approved and merged
      - name: Check if PR checks were successful
        id: passing-checks
        run: gh pr status | grep -A2 "Current branch" | grep -q "Checks passing"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve dependabot PR
        run: gh pr review --approve "$PR_BRANCH"
        shell: bash
        env:
          PR_BRANCH: ${{ inputs.prBranch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_BRANCH"
        env:
          PR_BRANCH: ${{ inputs.prBranch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
