name: Spyrius Labeler

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-labels:
    name: Add Labels
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add reviewers as assignees
        uses: actions/github-script@v5
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const githubToken = secrets.GITHUB_TOKEN;

            // Fetch PR to get the list of reviewers
            const { data: prData } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber,
            });

            const reviewers = prData.requested_reviewers.map(reviewer => reviewer.login);

            // Add reviewers as assignees
            if (reviewers.length > 0) {
              await github.rest.issues.addAssignees({
                owner,
                repo,
                issue_number: prNumber,
                assignees: reviewers,
              });
            }
          repo-token: ${{ secrets.GITHUB_TOKEN }}
